[package]
name = "hyperbee-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_builder = "0.12.0"
hypercore = "0.12.1"
prost = "0.12.1"
random-access-storage = "5.0.0"
tokio = { version = "1.34.0", features = ["macros", "rt"] }

[build-dependencies]
prost-build = "0.12.1"
